apiVersion: v1
kind: Service
metadata:
  name: argocd-node-port
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30900
    protocol: TCP
    name: access