kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    labels:
      junovfx/node: service
      ingress-ready: "true"
    extraPortMappings:
      - containerPort: 30900
        hostPort: 30900
        protocol: TCP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
