image: aldmbmtl/cluster-builder:v0.0.1                      # name of the container registry to pull the Cluster-Builder from
namespace: argocd                                           # namespace to deploy the Cluster-Builder to. Needs to be the same as where Argo is

projects:
  - code:                                                   # name, this is what it will be called in ArgoCD
    active:                                                 # active, specifies it the project should be deployed or "put to sleep"
    repo: https://github.com/juno-fx/Orion-Deployment.git   # repo, the git repository to pull the project from
    branch: main                                            # branch, the branch to pull the project from
    private:                                                # private, allows for NetworkPolicies to be created to isolate the project
                                                            #    from external traffic. Essentially disabling the internet and all possible
                                                            #    project cross talk.
