image: aldmbmtl/cluster-builder:v0.0.1                      # name of the container registry to pull the Cluster-Builder from
namespace: argocd                                           # namespace to deploy the Cluster-Builder to. Needs to be the same as where Argo is

projects:
  - code:                                                   # name, this is what it will be called in ArgoCD
    active:                                                 # active, specifies it the project should be deployed or "put to sleep"
    private:                                                # private, allows for NetworkPolicies to be created to isolate the project
                                                            #    from external traffic. Essentially disabling the internet and all possible
                                                            #    project cross talk.
    repo: https://github.com/juno-fx/Orion-Deployment.git   # repo, the git repository to pull the project from
    branch: main                                            # branch, the branch to pull the project from
    values:
      repo:                                                 # the git repository to pull the values from
      branch:                                               # the branch to pull the values from
      files:
        - values.yaml                                       # the file to pull the values from
    addons:
      - repo:                                               # repo, the git repository to pull the addon from
        branch:                                             # branch, the branch to pull the addon from
        valuesFiles:
          - values.yaml                                     # the file to pull the values from
    manifests:
      - repo:                                               # repo, the git repository to pull the manifests from
        branch:                                             # branch, the branch to pull the manifests from
        directory:                                          # directory, the directory to pull the manifests from
