registry: aldmbmtl    # name of the container registry to pull the Cluster-Builder from


projects:
#  - code:            # name, this is what it will be called in ArgoCD
#    active:          # active, specifies it the project should be deployed or "put to sleep"
#    private:         # private, allows for NetworkPolicies to be created to isolate the project
                      #   from external traffic. Essentially disabling the internet and all possible
                      #   project cross talk.
