apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: cluster-builder-sa-token
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: cluster-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-builder
    namespace: {{ .Values.namespace }}
