{{- range .Values.projects }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ lower .code }}
  namespace: {{ $.Values.namespace }}
{{/*  annotations:*/}}
{{/*    argocd.argoproj.io/hook: Sync*/}}
{{/*    argocd.argoproj.io/hook-delete-policy: HookSucceeded*/}}
spec:
  backoffLimit: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Never
      serviceAccountName: cluster-builder
      containers:
        - name: {{ lower .code }}
          image: {{ $.Values.image }}
          imagePullPolicy: Always
          env:
            {{- if .active }}
            - name: ACTION
              value: "install"
            {{- else }}
            - name: ACTION
              value: "uninstall"
            {{- end }}
            - name: NAME
              value: {{ lower .code }}
---
{{- end }}