{{- range .Values.projects }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ lower .code }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Never
      serviceAccountName: cluster-builder
      containers:
        - name: {{ lower .code }}
          image: {{ $.Values.image }}
          imagePullPolicy: Always
          env:
            {{- if .active }}
            - name: ACTION
              value: "install"
            {{- else }}
            - name: ACTION
              value: "uninstall"
            {{- end }}
            - name: NAME
              value: {{ lower .code }}
---
{{- if .active }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ lower .code }}
  namespace: argocd
spec:
  project: default
  destination:
    server: https://{{ lower .code }}.{{ lower .code }}.svc.cluster.local
    namespace: default

  sources:
    {{- range .addons }}
    - path: .
      repoURL: {{ .repo }}
      targetRevision: {{ .branch }}
      helm:
        parameters:
          {{- range $key, $value := $.Values.extra }}
            - name: {{ $key }}
              value: {{ $value }}
          {{- end }}
        valueFiles:
          {{- range .valuesFiles }}
          - $values/{{ . }}
          {{- end }}
    {{- end }}
    {{- range .manifests }}
    - path: {{ .directory }}
      repoURL: {{ .repo }}
      targetRevision: {{ .branch }}
      directory:
        recurse: true
    {{- end }}
    - path: .
      repoURL: {{ .repo }}
      targetRevision: {{ .branch }}
      helm:
        parameters:
          - name: show
            value: {{ lower .code }}
          {{- range $extra }}
          - name: {{ . }}
            value: {{ . }}
          {{- end }}
        valueFiles:
          {{- range .values.files }}
          - $values/{{ . }}
          {{- end }}

    - repoURL: {{ .values.repo }}
      targetRevision: {{ .values.branch }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
---
{{- end }}
{{- end }}
